# Generated by https://github.com/DeterminateSystems/nix-installer, version 0.8.0.
bash-prompt-prefix = (nix:$name)\040
build-users-group = nixbld
auto-optimise-store = true
experimental-features = nix-command flakes
extra-nix-path = nixpkgs=flake:nixpkgs